addons:
  apt:
    packages:
      - automake
  homebrew:
    - automake
  pkg:
    - automake
language: c
notifications:
  email: false
os:
  - freebsd
  - linux
  - osx
script:
  - aclocal
  - autoheader
  - automake -a -c
  - autoconf
  - ./configure --disable-dependency-tracking CC=clang CFLAGS="-Ofast -Wall -Werror -march=native" LD=clang LDFLAGS="-Wl,-s"
  - make
