jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Install dependencies
        run: sudo apt-get install automake -y
      - name: Run aclocal
        run: aclocal
      - name: Run autoheader
        run: autoheader
      - name: Run automake
        run: automake -a -c
      - name: Run autoconf
        run: autoconf
      - name: Configure
        run: ./configure --disable-dependency-tracking CC=clang CFLAGS="-Oz -Wall -Werror -Wextra -fno-exceptions -fno-rtti" LD=clang LDFLAGS="-Wl,-s -fuse-ld=lld"
      - name: Run make
        run: make
name: Build
on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '.editorconfig'
      - '.github/workflows/codeql.yml'
      - '.github/workflows/docker.yml'
      - '.gitignore'
      - 'AUTHORS'
      - 'COPYING'
      - 'ChangeLog'
      - 'Dockerfile'
      - 'NEWS'
      - 'README'
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '.editorconfig'
      - '.github/workflows/codeql.yml'
      - '.github/workflows/docker.yml'
      - '.gitignore'
      - 'AUTHORS'
      - 'COPYING'
      - 'ChangeLog'
      - 'Dockerfile'
      - 'NEWS'
      - 'README'
