name: build
on:
  push:
    branches: [ main ]
jobs:
  build-on-ubuntu:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Install dependencies
        run: sudo apt-get install automake -y
      - name: Run aclocal
        run: aclocal
      - name: Generate empty files
        run: touch ChangeLog NEWS
      - name: Rename README
        run: mv README.md README
      - name: Run automake
        run: automake -a -c
      - name: Run autoconf
        run: autoconf
      - name: Configure
        run: ./configure CC=clang CFLAGS="-Ofast -Wall -Werror -march=native" LD=clang LDFLAGS="-Wl,-s"
      - name: Run make
        run: make
