jobs:
  docker:
    if: github.ref_type == 'branch'
    name: Docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          path: /tmp/.buildx-cache
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Build
        uses: docker/build-push-action@v3
        with:
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
          context: .
          file: conf/hub/Dockerfile
          push: false
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}
      - name: Move cache
        run: |
          rm -fr /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
  github:
    if: github.ref_type == 'branch'
    name: GitHub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Install dependencies
        run: sudo apt-get install automake -y
      - name: Run aclocal
        run: |
          cd autotools
          aclocal
      - name: Run autoheader
        run: |
          cd autotools
          autoheader
      - name: Run automake
        run: |
          cd autotools
          automake -a -c
      - name: Run autoconf
        run: |
          cd autotools
          autoconf
      - name: Configure
        run: |
          mkdir -pv build
          cd build
          ../autotools/configure --disable-dependency-tracking CC=clang CFLAGS="-Oz -Wall -Werror -Wextra -flto -fno-plt" LD=clang LDFLAGS="-Wl,-s -flto -fno-plt -fuse-ld=lld"
      - name: Run make
        run: |
          cd build
          make
name: Build
on:
  pull_request:
    branches:
      - '**'
    paths-ignore:
      - '*.md'
      - '.clang-format'
      - '.editorconfig'
      - '.github/dependabot.yml'
      - '.github/workflows/codeql.yml'
      - '.github/workflows/mingw.yml'
      - '.github/workflows/publish.yml'
      - '.gitignore'
      - '.vscode/'
      - 'LICENSE'
      - 'conf/apt/'
      - 'conf/mingw/'
      - 'conf/x86_64-w64-mingw32/'
  push:
    branches:
      - '**'
    paths-ignore:
      - '*.md'
      - '.clang-format'
      - '.editorconfig'
      - '.github/dependabot.yml'
      - '.github/workflows/codeql.yml'
      - '.github/workflows/mingw.yml'
      - '.github/workflows/publish.yml'
      - '.gitignore'
      - '.vscode/'
      - 'LICENSE'
      - 'conf/apt/'
      - 'conf/mingw/'
      - 'conf/x86_64-w64-mingw32/'
    tags-ignore:
      - '**'
