jobs:
  docker:
    if: github.ref_type == 'branch'
    name: Docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          path: /tmp/.buildx-cache
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build
        uses: docker/build-push-action@v2
        with:
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
          context: .
          push: false
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:latest
      - name: Move cache
        run: |
          rm -fr /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
  github:
    if: github.ref_type == 'branch'
    name: GitHub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Install dependencies
        run: sudo apt-get install automake -y
      - name: Run aclocal
        run: aclocal
      - name: Run autoheader
        run: autoheader
      - name: Run automake
        run: automake -a -c
      - name: Run autoconf
        run: autoconf
      - name: Configure
        run: ./configure --disable-dependency-tracking CC=clang CFLAGS="-Oz -Wall -Werror -Wextra -fno-exceptions -fno-rtti" LD=clang LDFLAGS="-Wl,-s -fuse-ld=lld"
      - name: Run make
        run: make
name: Build
on:
  pull_request:
    paths-ignore:
      - '**.md'
      - '.editorconfig'
      - '.github/workflows/codeql.yml'
      - '.github/workflows/publish.yml'
      - '.gitignore'
      - 'AUTHORS'
      - 'COPYING'
      - 'ChangeLog'
      - 'NEWS'
      - 'README'
      - 'README.md'
  push:
    paths-ignore:
      - '**.md'
      - '.editorconfig'
      - '.github/workflows/codeql.yml'
      - '.github/workflows/publish.yml'
      - '.gitignore'
      - 'AUTHORS'
      - 'COPYING'
      - 'ChangeLog'
      - 'NEWS'
      - 'README'
      - 'README.md'
