env:
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/wol
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | \
          docker login --password-stdin -u ${{ secrets.DOCKERHUB_USERNAME }}
      - name: Build a docker image
        run: |
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          VERSION=$(echo "$VERSION" | sed -e 's/^v//')
          docker build \
            --label "org.opencontainers.image.version=$VERSION" \
            -t "$IMAGE_NAME" \
            .
          MINOR_VERSION=$(echo $VERSION | sed -n "s/^\([0-9]*.[0-9]*\).[0-9]*$/\1/p")
          [[ ${#MINOR_VERSION} -gt 0 ]] && \
            docker tag "$IMAGE_NAME" "$IMAGE_NAME:$MINOR_VERSION"
          MAJOR_VERSION=$(echo $VERSION | sed -n "s/^\([0-9]*\).[0-9]*.[0-9]*$/\1/p")
          [[ ${#MAJOR_VERSION} -gt 0 ]] && \
            docker tag "$IMAGE_NAME" "$IMAGE_NAME:$MAJOR_VERSION"
          docker tag "$IMAGE_NAME" "$IMAGE_NAME:$VERSION"
      - name: Push the built image to Docker Hub
        run: |
          docker push --all-tags "$IMAGE_NAME"
      - name: Patch the description to Docker Hub
        uses: peter-evans/dockerhub-description@v2
        with:
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: ${{ secrets.DOCKERHUB_USERNAME }}/wol
          short-description: Wake-On-LAN Client
          username: ${{ secrets.DOCKERHUB_USERNAME }}
name: Docker
on:
  create:
    tags:
      - 'v[0-9]+(\.[0-9]+)*'
