jobs:
  mingw:
    if: github.ref_type == 'branch'
    name: Cross Compile for MinGW
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-buildx-mingw-${{ github.sha }}
          path: /tmp/.buildx-mingw-cache
          restore-keys: |
            ${{ runner.os }}-buildx-mingw-
      - name: Build
        uses: docker/build-push-action@v3
        with:
          cache-from: type=local,src=/tmp/.buildx-mingw-cache
          cache-to: type=local,dest=/tmp/.buildx-mingw-cache-new,mode=max
          context: .
          file: conf/mingw/Dockerfile
          load: true
          push: false
      - name: Move cache
        run: |
          rm -fr /tmp/.buildx-mingw-cache
          mv /tmp/.buildx-mingw-cache-new /tmp/.buildx-mingw-cache
name: MinGW
on:
  push:
    branches:
      - '**'
    paths-ignore:
      - '*.md'
      - '.clang-format'
      - '.editorconfig'
      - '.github/dependabot.yml'
      - '.github/workflows/build.yml'
      - '.github/workflows/codeql.yml'
      - '.github/workflows/publish.yml'
      - '.gitignore'
      - '.vscode/'
      - 'LICENSE'
      - 'autotools/'
      - 'conf/apt/'
      - 'conf/hub/'
      - 'conf/x86_64-w64-mingw32/'
    tags-ignore:
      - '**'
