jobs:
  mingw:
    if: github.ref_type == 'branch'
    name: Cross Compile for MinGW
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-buildx-mingw-${{ github.sha }}
          path: /tmp/.buildx-mingw-cache
          restore-keys: |
            ${{ runner.os }}-buildx-mingw-
      - name: Build
        uses: docker/build-push-action@v2
        with:
          cache-from: type=local,src=/tmp/.buildx-mingw-cache
          cache-to: type=local,dest=/tmp/.buildx-mingw-cache-new,mode=max
          context: .
          file: conf/mingw/Dockerfile
          push: false
      - name: Move cache
        run: |
          rm -fr /tmp/.buildx-mingw-cache
          mv /tmp/.buildx-mingw-cache-new /tmp/.buildx-mingw-cache
name: MinGW
on:
  push:
    branches:
      - devel
      - main
